### ISSUE TITLE
Do we remove WARNING option?

### ISSUE THREAD

**Issue by NickNaso** [NickNaso/hertzy#10]
I want discuss if the WARNING option is really useful and if we can keep it without many complications.

**Comment by mauro-d** [comment]
The actual implementation of the WARNING option leads to a not solid behaviour.
The actual API lets the user switch the option _on_ and _off_ at any point and the actual implementation is not calling always our updateListeners function, causing inconsistency between our listener counter and Node.js' [counter](https://nodejs.org/api/events.html#events_emitter_listenercount_eventname).
Because we have an event emitter for every _frequency_, i can see an API to set a warning based on a specific frequency:
```javascript
Hertzy.warning('user', true)
```
On the other hand, at the moment, we could leave unchanged the Node's max listeners and remove, at least temporarily, this functionality.

**Comment by NickNaso** [comment]
Maybe it's possible to keep the WARNING options with the following changes to `updateListeners` function:

```js
function updateListeners(evt, type) {
        let evts = _ee.eventNames()
        let evtCount = _ee.listenerCount(evt)
        let maxCount = 0
        for (let evt of evts) {
            if (_ee.listenerCount(evt) > maxCount) {
                maxCount = _ee.listenerCount(evt)
            }
        }
        switch (type) {
            case actions.ON:
                /*if (_eeCounter.has(evt)) {
                    const evtNextNr = _eeCounter.get(evt) + 1
                    if (evtNextNr > _ee.getMaxListeners() &&
                        evtNextNr > Math.max(_eeCounter.values())) {
                        _ee.setMaxListeners(evtNextNr)
                    }
                    _eeCounter.set(evt, evtNextNr)
                } else {
                    _eeCounter.set(evt, 1)
                }*/
                if ((evtCount + 1) > maxCount && (evtCount + 1) > _ee.getMaxListeners()) {
                    _ee.setMaxListeners(evtCount + 1)
                }
                break
            case actions.OFF:
                /*if (_eeCounter.has(evt)) {
                    const evtPrevNr = _eeCounter.get(evt) - 1
                    if (evtPrevNr > 0) {
                        if (evtPrevNr > _ee.getMaxListeners() &&
                            evtPrevNr > Math.max(_eeCounter.values())) {
                            _ee.setMaxListeners(evtPrevNr)
                        }
                        _eeCounter.set(evt, evtPrevNr)
                    } else {
                        _eeCounter.delete(evt)
                    }
                }*/
                if ((evtCount - 1) > maxCount && (evtCount - 1) > _ee.getMaxListeners()) {
                    _ee.setMaxListeners(evtCount - 1)
                }
                break
            default:
                throw new Error('Hertzy: type need to be one of the following ' +
                    'supported actions [on, off]')
        }
    }
```
I need to investigate more deeply, but in the mean time I post the idea.

**Comment by mauro-d** [comment]
Hey Nick, i made some work on this and atm i ended up here:
```javascript
function on(ee, evt, frequencies) {
    if (Hertzy.WARNING) {
        resetFrequenciesListeners(frequencies) // Reset all frequencies to DEFAULT_MAX_LISTENERS
    } else {
        const evtCount = ee.listenerCount(evt) + 1
        const eeMaxCount = getFrequencyMaxListeners(getFrequencyStats(ee))
        if (evtCount > DEFAULT_MAX_LISTENERS && evtCount > ee.getMaxListeners() && evtCount > eeMaxCount) {
            ee.setMaxListeners(evtCount)
        }
        adjustFrequenciesListeners(frequencies, ee) // Adjust all other frequencies' max listeners
    }
}

function off(ee, evt, frequencies) {
    if (Hertzy.WARNING) {
        resetFrequenciesListeners(frequencies) // Reset all frequencies to DEFAULT_MAX_LISTENERS
    } else {
        const evtCount = ee.listenerCount(evt) - 1
        const stats = getFrequencyStats(ee)
        stats[evt] = evtCount
        const eeMaxCount = getFrequencyMaxListeners(stats)
        if (evtCount > DEFAULT_MAX_LISTENERS) {
            ee.setMaxListeners(evtCount)
        }
        adjustFrequenciesListeners(frequencies, ee) // Adjust all other frequencies' max listeners
    }
}
```
As you can see `adjustFrequenciesListeners` is executed every time occur an _on_ or an _off_, all this because the user could switch `Hertzy.WARNING` at any point, so we should check every time that all the frequencies have the right settings. Probably, we could avoid this behaviour storing the previous `WARNING` value and comparing it with the actual one.
At the moment, we handle the `WARNING` only during listener attaching or removing, so if the `WARNING ` is set and then doesn't occur a listener attaching or removing, nothing will happen until one of the previuos action will be performed.
I thought if ti makes sense to use a function to handle the warning:
```javascript
Hertzy.warning(true)
```
Ok, let me know what you think about all this.

**Comment by mauro-d** [comment]
About my previous comment, probably it's not necessary the warning function, think at something like this:
```javascript
const cb = () => {}
const userF = Hertzy.tune('user')
const orderF = Hertzy.tune('order')
const mailF = Hertzy.tune('email')

mailF.on('mail:sent', cb)
mailF.on('mail:sent', cb)

userF.on('user:add', cb)

orderF.on('order:paid', cb)
orderF.on('order:paid', cb)
    
userF.on('user:add', cb)
Hertzy.WARNING = true
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.off('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', cb)
orderF.on('order:cancelled', 
orderF.on('order:cancelled', cb)
Hertzy.WARNING = false
orderF.on('order:cancelled', cb)
orderF.off('order:cancelled', cb)
userF.on('user:add', cb)
userF.on('user:add', cb)
```
even if the last warning is switched to false, node will print the warning anyway because in the mean time 'order:cancelled' has exceeded the max listener limit. So, should be ok to leave the things as they are.

**Comment by NickNaso** [comment]
Hi @mauro-d I agree with you, continue to work on your solution like you reported above.

**Comment by mauro-d** [comment]
I've pushed some work i've done here: [https://github.com/mauro-d/hertzy/commit/9d26a460ce95e6c57e47c0eac0d88af88b73dc44](https://github.com/mauro-d/hertzy/commit/9d26a460ce95e6c57e47c0eac0d88af88b73dc44)[WIP]

**Comment by NickNaso** [comment]
@mauro-d  Good I will take a look for the Monday 4th June.
